### ISSUE TITLE
css选择器相关说明

### ISSUE THREAD

**Issue by Pengxi92** [Pengxi92/blog#3]
随着CSS3的到来，css的选择器也有了新的成员。本文将综合前端开发中常用的CSS3选择器，希望对大家有所帮助。

#### 通用元素选择器 *

示例：
```css
* {  
 margin: 0;  
}
```

该示例是选择页面上的全部元素，把`margin`设为0

#### ID选择器 #ID

示例：

```css
#header {  
 margin: 0;  
}
```

该示例是选择页面上`id`为`header`的元素，把`margin`设为0。

*注：ID选择器是CSS中效率最高的选择器，使用的时候要保证ID的唯一性。*

#### 类选择器 .class

示例：

```css
.colorClass {  
  color: red;
}
```

该示例是选择页面上`class`为`colorClass`的元素，把`color`设为`red`。

*注：类选择器效率低于ID选择器，一个页面可以有多个class，并且class可以放在不同的标签中使用。*

#### 标签选择器 X

示例：

```css
li{  
   margin: 0;
}
```

该示例是选择页面所有`li`元素，把`margin`设为0。

#### 伪类选择器 :X

[CSS伪类](http://www.w3school.com.cn/css/css_pseudo_classes.asp)用于向某些选择器添加特殊的效果。

* 锚伪类

在支持 CSS 的浏览器中，链接的不同状态都可以不同的方式显示，这些状态包括：活动状态，已被访问状态，未被访问状态，和鼠标悬停状态。

示例：

```css
a:link {color: #FF0000}/* 未访问的链接 */
a:visited {color: #00FF00}/* 已访问的链接 */
a:hover {color: #FF00FF}/* 鼠标移动到链接上*/
a:active {color: #0000FF}/* 选定的链接 */
```

该示例是选择页面所有`a`元素，在不同的状态时显示不同的颜色。

*提示：在 CSS 定义中，a:hover 必须被置于 a:link 和 a:visited 之后，才是有效的。*

*提示：在 CSS 定义中，a:active 必须被置于 a:hover 之后，才是有效的。*

*提示：伪类名称对大小写不敏感。*

* :focus

示例：

```css
input:focus{
    background-color: yellow;
}
```

该示例是选择页面的`input`元素，在元素获得焦点时，设置`background-color`为`yellow`。

* :first-child

示例：

```css
p:first-child {
  color: red;
}
```

该示例是选择页面的第一个`p`元素，设置`color`为`red`。

* :last-child

示例：

```css
p:last-child {
  color: red;
}
```

该示例是选择页面的最后一个`p`元素，设置`color`为`red`。

* :nth-child(n)

选择器匹配属于其父元素的第`n`个子元素，不论子元素的类型（第一个子元素的下标是 1）。

```css
/* 设置所有元素的第一个子元素的背景色为red */
:nth-child(1) {
  background: red;
}

/*
* 设置所有元素的第一个子元素的每个p的背景色为red
* 即该元素满足2个条件：为第一个子元素；元素类型为p
*/
p:nth-child(1) {
  background: red;
}

/*
* 设置所有元素的下标为奇数子元素的每个p的背景色为red
* 即该元素满足2个条件：子元素的下标为奇数；元素类型为p
*/
p:nth-child(odd) {
  background: red;
}

/*
* 设置所有元素的下标为偶数子元素的每个p的背景色为red
* 即该元素满足2个条件：子元素的下标为偶数；元素类型为p
*/
p:nth-child(even) {
  background: red;
}

/*
* 设置下标为3的倍数的子元素的每个p的背景色为red
* 即该元素满足2个条件：子元素的下标为3的倍数；元素类型为p
* 3n+0为公式 (an + b)：表示周期的长度，n 是计数器（从 0 开始），b 是偏移值
*/
p:nth-child(3n+0) {
  background: red;
}
```

* X:nth-last-child(n)

选择器匹配属于其父元素的第`n`个子元素，不论子元素的类型（最后一个子元素的下标是 1）。
用法同`nth-child`。

* X:nth-of-type(n)

匹配属于父元素的特定类型的第`n`个子元素的每个元素，特定类型为X（第一个子元素的下标是 1）。

`n`值的写法同`nth-child`。与`nth-child`的区别在于子元素的范围不同，**`nth-child`针对所有子元素，`nth-of-type`针对特定类型的子元素**。

* X:nth-last-of-type(n)

匹配属于父元素的特定类型的第`n`个子元素的每个元素，特定类型为X（最后一个子元素的下标是 1）。
用法同`nth-of-type`。

* X:first-of-type

示例：

```css
p:first-of-type{
  background:#ff0000;
}
```

匹配属于父元素的首个`p`元素，并设置`background`为`#ff0000`。

* X:last-of-type

示例：

```css
p:last-of-type{
  background:#ff0000;
}
```

匹配属于父元素的最后一个`p`元素，并设置`background`为`#ff0000`。

* X:only-child

匹配父元素下仅有的一个子元素，即父元素中只有一个子元素。

示例：

```html
<style>
  p:only-child{
    background:#ff0000;
  }
</style>
</head>

<body>
  <div>
    <p>这是一个段落。-样式生效</p>
  </div>
  <div>
    <span>这是一个 span。</span>
    <p>这是一个段落。-样式不生效</p>
  </div>
</body>
```

* X:only-of-type

用法同`only-child`。

#### 标签组合选择器 X Y

示例：

```css
li a {  
   margin: 0;
}
```

该示例是选择页面`li`中的所有子元素`a`，把`margin`设为0。

#### 子元素选择器 X>Y

示例：

```css
span>a {  
   margin: 0;
}
```

该示例是选择页面`span`中的第一个子元素`a`，把`margin`设为0。

#### 毗邻元素选择器 X+Y

示例：

```css
span+a {  
   margin: 0;
}
```

该示例是选择页面紧随`span`的同级元素`a`，把`margin`设为0。

#### element1~element2 选择器 X~Y

示例：

```css
span~a {  
   margin: 0;
}
```

该示例是选择页面`span`之后的所有同级元素`a`，把`margin`设为0。

#### 属性选择器 X[title]

示例：

```css
/*
* 匹配有`title`属性的`a`元素
*/
a[title] {  
   color: green;
}

/*
* 匹配有`href`属性，并且`href`的值为`http://js8.in`的`a`元素
*/
a[href="http://js8.in"] {  
  color: green;
}

/*
* 匹配有`title`属性，并且`title`的值包含单词`flower`的`a`元素
* 本示例匹配title="tulip flower"，但不匹配title="tulip flowers"
*/
a[title~="flower"] {  
  color: green;
}

/*
* 匹配有`title`属性，并且`title`的值包含`flower`的`a`元素
* 本示例匹配title="tulip flower"，也匹配title="tulip flowers"
*/
a[title*="flower"] {  
  color: green;
}

/*
* 匹配有`lang`属性，并且`lang`的值以`en`开头的`a`元素
* `lang`的值必须是整个单词，比如 lang="en"，或者后面跟着连字符，比如 lang="en-us"
*/
a[lang|=en] {  
  color: green;
}

/*
* 匹配有`href`属性，并且`href`的值以`https`开头的`a`元素
*/
a[href^="https"] {  
  color: green;
}

/*
* 匹配有`href`属性，并且`href`的值以`.pdf`结尾的`a`元素
*/
a[href$=".pdf"] {  
  color: green;
}
```

#### :checked 选择器

示例：

```css
input:checked {  
   margin: 0;
}
```

该示例是匹配所有被选中的`input`（只用于单选按钮和复选框），把`margin`设为0。

#### :disabled 选择器

示例：

```css
input:disabled {
  background-color: #dddddd;
}
```

该示例是匹配所有被禁用的`input`（type="text"），把`background-color`设为`#dddddd`。

#### :enabled 选择器

示例：

```css
input:enabled {
  background-color: #dddddd;
}
```

该示例是匹配所有被启用的`input`（type="text"），把`background-color`设为`#dddddd`。

#### :empty 选择器

示例：

```css
p:empty {
  margin: '10px';
}
```

该示例是匹配所有空的`p`(没有包括文本节点在内的子元素)，把`margin`设为`10px`。

#### :root 选择器

示例：

```css
:root {
  background-color: #dddddd;
}
```

该示例是匹配文档根元素，把`background-color`设为`#dddddd`。

#### :not 选择器

示例：

```css
:not(p) {
  background-color: #dddddd;
}
```

该示例是匹配非`p`元素，把`background-color`设为`#dddddd`。

#### 伪元素选择器

伪类与伪元素的区别在于：有没有创建一个文档树之外的元素。

* :first-line

用于向文本的首行设置特殊样式。

示例：

```css
p:first-line {
  background-color: #dddddd;
}
```

该示例是匹配`p`元素的第一行文本，把`background-color`设为`#dddddd`。

* :first-letter

用于向文本的首字母设置特殊样式。

示例：

```css
p:first-letter {
  background-color: #dddddd;
}
```

该示例是匹配`p`元素文本的首字母，把`background-color`设为`#dddddd`。

*注："first-letter" 伪元素只能用于块级元素*

* :before

在元素的内容前面插入新内容。

示例：

```css
h1:before{
  content:url(logo.gif);
}
```

* :after

在元素的内容后面插入新内容。

示例：

```css
h1:after{
  content:url(logo.gif);
}
```
